name: biblio-compose

services:
  mysql:
    image: mysql:8.0.44-debian
    container_name: biblio-mysql
    environment:
      MYSQL_DATABASE: biblio
      MYSQL_ROOT_PASSWORD: root

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

    volumes:
      - db_data:/var/lib/mysql
      - ./biblio-init.sql:/docker-entrypoint-initdb.d/setup.sql

    networks:
      - biblio


  boot:
    # build:
      # context: /workspace/SOPRA-250905-GIT/quest-boot
      # context: ./quest-boot

    image: ajc/biblio:boot
    container_name: biblio-boot

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://biblio-mysql/biblio
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - biblio


  angular:
    image: ajc/biblio:angular
    container_name: biblio-angular

    ports:
      - 80:80

    depends_on:
      - boot

    networks:
      - biblio

volumes:
  db_data:
    name: biblio-db-data

networks:
  biblio:
    name: biblio
