name: biblio-compose

services:
  mysql:
    image: postgres:16
    container_name: biblio-postgres
    environment:
      POSTGRES_DB: biblio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./biblio-init.sql:/docker-entrypoint-initdb.d/setup.sql

    networks:
      - biblio


  boot:
    # build:
      # context: /workspace/SOPRA-250905-GIT/quest-boot
      # context: ./quest-boot

    image: ajc/biblio:quarkus
    container_name: biblio-quarkus

    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://biblio-postgres:5432/biblio
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: root

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - biblio


  angular:
    image: ajc/biblio:angular
    container_name: biblio-angular

    ports:
      - 80:80

    depends_on:
      - boot

    networks:
      - biblio

volumes:
  db_data:
    name: biblio-db-data

networks:
  biblio:
    name: biblio
